<a href="https://colab.research.google.com/github/itsmesaadali/Artificial-intelligence-Project/blob/main/Lab_Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AI Lab no 3

1. Create a 3x3 matrix with values ranging from 2 to 10, convert array to a float type. Write a
Python program to find the maximum and minimum value of flattened array.

In [ ]:
import numpy as np

# Step 1: Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.linspace(2, 10, 9) # 9 values evenly spaced from 2 to 10
matrix = matrix.reshape(3, 3)  # 9 values evenly reshape
matrix = matrix.astype(float)  # Step 2: Convert array to float type

print("3x3 Matrix:")
print(matrix)

# Step 3: Flatten the array
flattened = matrix.flatten()
print("\nFlattened Array: ", flattened)

# Step 4: Find maximum and minimum values
max_value = flattened.max()
min_value = flattened.min()

print("\nMaximum value:", max_value)
print("Minimum value:", min_value)

3x3 Matrix:
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

Flattened Array:  [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]

Maximum value: 10.0
Minimum value: 2.0
